### ISSUE TITLE
SMS Flow for positive tests

### ISSUE THREAD

**Issue by pjaspers** [covid-be-app/cwa-app-ios#269]
[x] None of the other issue templates apply to this issue.

Hi there! I've complained about this on the interwebs, and searched the https://coronalert.be/nl/ for a contact page, but couldn't find one, so as a last resort, I'm bothering you, sorry. Can someone update the flow you need to go through when you're going to get tested?

I think it's explained here: https://devside.atlassian.net/wiki/spaces/CD/pages/11469091/iOS, and I can see in the iOS app that you're taking over the URL, and using javascript to prefill that form. (I would try and make the webpage better instead of making the app do this, but that's another discussion)

But apart from a small note in the release notes of the app, I haven't see any mention of it. If the doctors don't need to get the 17 digit code, this would save quite some time. If people can retroactively link test and app, this would probably help in getting more positive tests into the app.

Twitter:
[Complaining about the lack of instructions](https://twitter.com/pjaspers/status/1318652622958743560)
[Where I dug into the SMS](https://twitter.com/pjaspers/status/1318647008870256642)

**Comment by ir-fuel** [comment]
This is still not rolled out. The apps have been prepared for this, but we need a lot of users to be updated to the latest version or otherwise lots of people could receive an SMS without the app being capable of opening it (since they are still running an old version of Coronalert).

But the basics stay the same. The person registering the test (doctor or other) will need to enter the code generated by your app. The SMS scenario is only supposed to be used for those cases where it didn't happen for some reason. If test requests are received without an app code, those numbers will be notified through SMS to link their app. This is not related to a test result FYI. When the SMS will be sent out the test result is still unknown.

**Comment by pjaspers** [comment]
> This is still not rolled out. The apps have been prepared for this, but we need a lot of users to be updated to the latest version or otherwise lots of people could receive an SMS without the app being capable of opening it (since they are still running an old version of Coronalert).

They would visit the webform, no? So worst case scenario, that page needs to be update to include that you need to copy over your test code to that form.

> The SMS scenario is only supposed to be used for those cases where it didn't happen for some reason.

Since it's copying over a 17-digit number, either over telephone or visually, there are a lot of reasons this fails to happen.

E.g.

- "We just don't have the time, to explain it to people and wait for the code, some people can't use their phones"
- "I added it but the forms were not supporting it"
- "Sometimes it fails, because the submission date is different"

I think, not having to do the code up front could help a lot with app usage, and it seems like the SMS flow would do just that.

**Comment by ir-fuel** [comment]
This is a discussion you should have with Sciensano / the government I think. It's a bit out of scope (and out of our control) for the iOS Github repository ;)

**Comment by pjaspers** [comment]
👍 Agreed! You were just the only contact point I could find :)
